import Mixin from '@ember/object/mixin';
import { notEmpty, not, and, equal } from '@ember/object/computed';

export default Mixin.create({
  name: null,
  city: null,
  address: null,
  address2: null,
  zip: null,
  state: null,
  subdomain: null,
  isEnabled: true,

  isCreateView: true,

  mainContactName: null,
  mainContactEmail: null,
  mainContactPhone: null,
  billingContactName: null,
  billingContactEmail: null,
  billingContactPhone: null,
  techincalContactName: null,
  techincalContactEmail: null,
  techincalContactPhone: null,
  healthicitySalesName: null,
  healthicitySalesEmail: null,
  healthicitySalesPhone: null,
  healthicityAccountManagerName: null,
  healthicityAccountManagerEmail: null,
  healthicityAccountManagerPhone: null,
  selectedProducts: null,

  auditManagerCustomerType: null,
  auditManagerUserLicenses: 1,
  auditManagerEmrs: null,
  auditManagerClientTypes: null,

  wantsDeliverEmails: false,

  formProperties: null,

  touchables: [
    'nameIsTouched',
    'cityIsTouched',
    'addressMainIsTouched',
    'stateIsTouched',
    'zipIsTouched',
    'mainContactNameIsTouched',
    'mainContactEmailIsTouched',
    'mainContactNameIsTouched',
    'healthicitySalesNameIsTouched',
    'healthicityAccountManagerNameIsTouched',
    'amTrialEndDateIsTouched',
    'cmTrialEndDateIsTouched',
    'fmTrialEndDateIsTouched',
    'paTrialEndDateIsTouched',
    'tcTrialEndDateIsTouched',
    'subDomainIsTouched',
    'productGroupHasBeenTouched',
    'auditManagerAuditeeTypeIsTouched'
  ],

  hasName: notEmpty('name'),
  blankName: not('hasName'),
  hasCity: notEmpty('city'),
  blankCity: not('hasCity'),
  hasAddressMain: notEmpty('address'),
  blankAddressMain: not('hasAddressMain'),
  hasState: notEmpty('state'),
  blankState: not('hasState'),
  hasZip: notEmpty('zip'),
  blankZip: not('hasZip'),
  hasSubDomain: notEmpty('subdomain'),
  blankSubDomain: not('hasSubDomain'),
  hasMainContactName: notEmpty('mainContactName'),
  blankMainContactName: not('hasMainContactName'),
  hasMainContactEmail: notEmpty('mainContactEmail'),
  blankMainContactEmail: not('hasMainContactEmail'),
  hasHealthicitySalesName: notEmpty('healthicitySalesName'),
  blankHealthicitySalesName: not('hasHealthicitySalesName'),
  hasHealthicityAccountManagerName: notEmpty('healthicityAccountManagerName'),
  blankHealthicityAccountManagerName: not('hasHealthicityAccountManagerName'),

  nameIsInvalid: and('blankName', 'nameIsTouched'),
  nameIsValid: not('nameIsInvalid'),
  cityIsInvalid: and('blankCity', 'cityIsTouched'),
  cityIsValid: not('cityIsInvalid'),
  addressMainIsInvalid: and('blankAddressMain', 'addressMainIsTouched'),
  addressMainIsValid: not('addressMainIsInvalid'),
  stateIsInvalid: and('blankState', 'stateIsTouched'),
  stateIsValid: not('stateIsInvalid'),
  zipIsInvalid: and('blankZip', 'zipIsTouched'),
  zipIsValid: not('zipIsInvalid'),
  subDomainIsInvalid: and('blankSubDomain', 'subDomainIsTouched', 'isCreateView'),
  subDomainIsValid: not('subDomainIsInvalid'),
  mainContactNameIsInvalid: and('blankMainContactName', 'mainContactNameIsTouched'),
  mainContactNameIsValid: not('mainContactNameIsInvalid'),
  mainContactEmailIsInvalid: and('blankMainContactEmail', 'mainContactEmailIsTouched'),
  mainContactEmailIsValid: not('mainContactEmailIsInvalid'),
  healthicitySalesNameIsInvalid: and('blankHealthicitySalesName', 'healthicitySalesNameIsTouched'),
  healthicitySalesNameIsValid: not('healthicitySalesNameIsInvalid'),
  healthicityAccountManagerNameIsInvalid: and('blankHealthicityAccountManagerName', 'healthicityAccountManagerNameIsTouched'),
  healthicityAccountManagerNameIsValid: not('healthicityAccountManagerNameIsInvalid'),

  hasProductSelected: notEmpty('selectedProducts'),
  productsAreEmpty: not('hasProductSelected'),
  productIsInvalid: and('productsAreEmpty', 'productGroupHasBeenTouched'),
  productIsValid: not('productIsInvalid'),

  auditManagerAuditeeTypesIsEmpty: not('auditManagerAuditeeTypes'),
  auditManagerAuditeeIsInvalid: and('auditManagerAuditeeTypesIsEmpty', 'auditManagerAuditeeTypeIsTouched', 'hasAuditManager'),
  auditManagerAuditeeTypesIsValid: not('auditManagerAuditeeIsInvalid'),
  auditManagerCustomerTypeIsNull: not('auditManagerCustomerType'),
  auditCustomerTypeIsInvalid: and('auditManagerCustomerTypeIsNull', 'hasAuditManager'),
  auditCustomerTypeIsValid: not('auditCustomerTypeIsInvalid'),

  amAccessType: 'standard',
  isAMTrialAccount: equal('amAccessType', 'trial'),
  hasAMEndDate: notEmpty('amTrialEndDate'),
  blankAMEndDate: not('hasAMEndDate'),
  amTrialEndDateIsInvalid: and('blankAMEndDate', 'isAMTrialAccount'),
  amTrialEndDateIsValid: not('amTrialEndDateIsInvalid'),

  cmAccessType: 'standard',
  isCMTrialAccount: equal('cmAccessType', 'trial'),
  hasCMEndDate: notEmpty('cmTrialEndDate'),
  blankCMEndDate: not('hasCMEndDate'),
  cmTrialEndDateIsInvalid: and('blankCMEndDate', 'isCMTrialAccount'),
  cmTrialEndDateIsValid: not('cmTrialEndDateIsInvalid'),

  // fmAccessType: 'standard',
  // isFMTrialAccount: equal('fmAccessType', 'trial'),
  // hasFMEndDate: notEmpty('fmTrialEndDate'),
  // blankFMEndDate: not('hasFMEndDate'),
  // fmTrialEndDateIsInvalid: and('blankFMEndDate', 'isFMTrialAccount'),
  // fmTrialEndDateIsValid: not('fmTrialEndDateIsInvalid'),

  // paAccessType: 'standard',
  // isPATrialAccount: equal('paAccessType', 'trial'),
  // hasPAEndDate: notEmpty('paTrialEndDate'),
  // blankPAEndDate: not('hasPAEndDate'),
  // paTrialEndDateIsInvalid: and('blankPAEndDate', 'isPATrialAccount'),
  // paTrialEndDateIsValid: not('paTrialEndDateIsInvalid'),

  // tcAccessType: 'standard',
  // isTCTrialAccount: equal('tcAccessType', 'trial'),
  // hasTCEndDate: notEmpty('tcTrialEndDate'),
  // blankTCEndDate: not('hasTCEndDate'),
  // tcTrialEndDateIsInvalid: and('blankTCEndDate', 'isTCTrialAccount'),
  // tcTrialEndDateIsValid: not('tcTrialEndDateIsInvalid'),

  allRequiredFieldsAreMet: and(
    'hasName',
    'hasCity',
    'hasAddressMain',
    'hasState',
    'hasZip',
    'hasSubDomain',
    'hasMainContactName',
    'hasMainContactEmail',
    'hasHealthicitySalesName',
    'hasHealthicityAccountManagerName',
    'hasProductSelected',
    'amTrialEndDateIsValid',
    'cmTrialEndDateIsValid'
    // 'fmTrialEndDateIsValid',
    // 'parialEndDateIsValid',
    // 'tcTrialEndDateIsValid',
    // 'auditCustomerTypeIsValid',
    // 'auditManagerAuditeeTypesIsValid'
  )

});
